name: NPM Installation

on:
  push:
    branches-ignore:
      - "dependabot/**"
  schedule:
  - cron: '0 0 * * *'
  workflow_dispatch:

env:
  FORCE_COLOR: 2
  NODE: 16

jobs:
  build:
    strategy:
      matrix:
        platform: [ubuntu-latest, windows-latest]
        node-version: [16.x, 17.x, 18.x]
    runs-on: ${{ matrix.platform }}
    steps:
      - name: Clone repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.node-version }}

      - name: Install npm dependencies
        run: npm install

      - name: Run build
        run: npm run build

      - name: Configure AWS credentials
        if: matrix.platform == 'ubuntu-latest' && github.ref == 'refs/heads/main'
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-2  

      - name: Upload to S3
        if: matrix.platform == 'ubuntu-latest' && github.ref == 'refs/heads/main'
        run: |
          aws s3 sync build/ s3://remind-manage-real-page --delete

      - name: Invalidate CloudFront Cache
        if: matrix.platform == 'ubuntu-latest' && github.ref == 'refs/heads/main'
        run: |
          aws cloudfront create-invalidation \
            --distribution-id E1S1AWIWUQPX49 \
            --paths "/*"

